name: personal-resume
on: push

jobs: 
  pnpm-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup pnpm
      uses: pnpm/action-setup@v3
      with: 
        version: 8.1.2
        run_install: true

    - name: Build PersonalResume site
      run: pnpm build